- name: install packages
  tags: apache2,lib-php
  apt:
    pkg:
      - "{{ apache_package_name  }}"
      - "{{ php_package_name  }}"
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: start service
  tags: service
  service:
    name: "{{ apache_service  }}"
    state: stopped
  notify: restart apache2.service
