---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update-cache: true

  - name: Installing Tree
    apt:
      name: tree
      state: latest

  - name: install apache_server
    apt:
      name: apache2
      state: latest

  - name: Remove Packages
    apt:
      name: apache2
      state: absent
