---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update-cache: true
    when: ansible_distribution == "CentOS" or ansible_distribution in ["Debian","Ubuntu"]

  - name: Installing Tree
    apt:
      name: tree
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache_server
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Remove Packages
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

# if we want to do all this stuff for CentOS we can simply change the -Module[name] and the packages[name] because it's different on CentOS distribution
