---

- hosts: all
  become: true
  tasks:

  - name: Install Clamav
    apt:
      pkg:
        - clamav
        - clamav-daemon
       state: latest
       update_cache: true
    when: ansible_distribution in ["Ubuntu","Debian"]


  - name: Update DB
    shell: |
      systemctl stop clamav-freshclam.service
      sudo freshclam
      systemctl start clamav-freshclam.service

  - name: Creates directory
    ansible.builtin.file:
      path: ~/clamav
      state: directory

  - name: Import config File
    copy:
      src: ~/clamav/clamav.sh
      dest: ~/clamav/clamav.sh

  - name: Import Config File
    copy:
      src: ~/clamav/clamd.sh
      dest: ~/clamav/clamd.sh

  - name: Crontab
    copy:
      content: "{{ * * * * * . ~/clamav/clamd.sh 2>/dev/null }}"
      dest: "/var/spool/cron/crontabs/$USER"
    when: ansible_distribution == "Ubuntu"
