#- name: restart_DB_clamav
#  tags: restart_DB
#  service:
#    name: "{{ clamav_DB  }}"
#    state: restarted
#    enabled: true

- name: restart apache2.service
  tags: restart_apache2
  service:
    name: "{{ apache_package_name  }}"
    state: started
    enabled: true

- name: restart sshd service
  tags: sshd
  service:
    name: sshd
    state: started
    enabled: true
