---

- hosts: dc_client
  become: true
  tasks:

  - name: Install Clamav
    apt:
      pkg:
        - clamav
        - clamav-daemon
      state: latest
      update_cache: true
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: add user
    tags: always
    user:
      name: amir
      group: root

  - name: add ssh-key for user
    tags: always
    authorized_key:
      user: amir
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKAbPyd2D56aHs9xE20WIYcDvc+pRTs2S6ZScJReCYWk ansible"

  - name: make it sudo_nopass
    tags: always
    copy:
      src: ~/sudo_amir
      dest: /etc/sudoers.d/amir
      owner: root
      group: root
      mode: 0440

  - name: show patterns
    tags: pattern
    shell: |
      echo "hello i am a devops ." > hello.sh

  - name: change patterns
    tags: pattern
    lineinfile:
      path: ~/hello.sh
      regexp: '^hello i am a devops'
      line: hello i am amir
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: COPYING.......
    tags: copy
    copy:
      src: /home/javande/directory.txt # ~
      dest: /home/{{ user }}/Documents/directory.txt # ~
      owner: root
      group: root
      mode: 0644

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restarting the httpd
    tags: httpd
    service:
      name: httpd
      state: restarted
      enable: true
    when: httpd.changed

- hosts: all
  become: true
  tasks:

  - name: Remove the useless Packages
    tags: autoremove
    apt:
       autoremove: yes
       purge: yes

  - name: Update the Packages
    tags: ubuntu
    apt:
      update-cache: true
    when: ansible_distribution == "Ubuntu"

  - name: Update the Packages
    tags: centos
    dnf:
      update_cache: true
    when: ansible_distribution == "CentOS"
