---

- hosts: dc_client
  become: true
  tasks:

   - name: Install Clamav
     apt:
       pkg:
         - clamav
         - clamav-daemon
       state: latest
       update_cache: true
     when: ansible_distribution in ["Ubuntu","Debian"]


   - name: show patterns
     shell: |
       echo "hello i'm using ansible ." > hello.sh


- hosts: all
  become: true
  tasks:

  - name: COPYING.......
    tags: copy
    copy:
      src: /home/javande/directory.txt # ~
      dest: /home/{{ user }}/Documents/directory.txt # ~
      owner: root
      group: root
      mode: 0644

- hosts: all
  become: true
  tasks:

  - name: Remove the useless Packages
    tags: autoremove
    apt:
       autoremove: yes
       purge: yes

  - name: Update the Packages
    tags: ubuntu
    apt:
      update-cache: true
    when: ansible_distribution == "Ubuntu"

  - name: Update the Packages
    tags: centos
    dnf:
      update_cache: true
    when: ansible_distribution == "CentOS"
