---

- hosts: all
  become: true
  tasks:

  - name: Installing Tree
    apt:
      name:
        - tree  #       - "{{ pkg1 }}"
        - apache2  #       - "{{ pkg2 }}"
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: Remove Packages
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

# if we want to do all this stuff for CentOS we can simply change the -Module[name] and the packages[name] because it's different on CentOS distribution
